<?php

/**
 * @file
 * Provides sample email send action with overriding templates.
 *
 */

/*
 * Email key
 */
define('MAIL_EDIT_TEST_EMAIL_KEY', 'mail_edit_test_email');
/*
 * Email subject ID
 */
define('MAIL_EDIT_TEST_SUBJECT', 1);
/*
 * Email body ID
 */
define('MAIL_EDIT_TEST_BODY', 2);

/*
 * Including Mail Editor API custom implementation
 */
include_once __DIR__ .'/mail_edit_test.inc';

/**
 * Implements hook_menu()
 */
function mail_edit_test_menu() {
    $items = array();
    $items['node/%node/send_mail'] = array(
        'title' => 'Send node by email',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('mail_edit_test_form', 1),
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 999,

    );
    return $items;
}

function mail_edit_test_form($form, &$form_state) {
    if (empty($form_state['build_info']['args'])) {
        drupal_not_found();
        return array();
    }
    $form = array();
    $form['recipient'] = array(
        '#type' => 'textfield',
        '#title' => t('Recipients email address'),
        '#required' => TRUE,
        '#description' => t('Seperate emails by comma'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );
    return $form;
}

function mail_edit_test_form_validate($form, &$form_state) {
    $emails = explode(',', $form_state['values']['recipient']);
    foreach($emails as $email) {
        if (! valid_email_address($email)) {
            form_set_error('recipient', t('You must provide valid email address'));
            break;
        }
    }
}

function mail_edit_test_form_submit($form, &$form_state) {
    $node = $form_state['build_info']['args'][0];
    _mail_edit_test_email_sendEmail($node, $form_state['values']['recipient']);
}

function _mail_edit_test_email_sendEmail($node, $to) {
    $params['node'] = $node;
    //drupal_mail should get language object so I create mock for this object, works fine
    $language = new stdClass;
    $language->language = $node->language;
    $mail = drupal_mail('mail_edit_test', MAIL_EDIT_TEST_EMAIL_KEY, $to, $language, $params);
    return empty($mail) ? NULL : $mail['result'];
}

/**
 * Implements hook_mail()
 */
function mail_edit_test_mail($key, &$message, $params) {
    switch ($key) {
        case MAIL_EDIT_TEST_EMAIL_KEY:
            $variables = array('node' => $params['node']);
            $language = $params['node']->language;
            $message['subject'] = drupal_html_to_text(_mail_edit_test_text(MAIL_EDIT_TEST_SUBJECT, $language, $variables));
            $message['body'][] = drupal_wrap_mail(drupal_html_to_text(_mail_edit_test_text(MAIL_EDIT_TEST_BODY, $language, $variables)));
            break;
    }
}

/**
 * Implements hook_mail_alter()
 *
 * @param $message message array
 */
function mail_edit_test_mail_alter(&$message) {
    if ($message['id'] != 'mail_edit_test_' . MAIL_EDIT_TEST_EMAIL_KEY) {
        return;
    }
    if (!$template = _mail_edit_load($message['id'], $message['language'])) {
        return;
    }
    $options['language'] = $message['language'];
    $data['node'] = $message['params']['node'];
    $message['subject'] = drupal_html_to_text(mail_edit_format($template['subject'], $data, $options));
    $message['body'] = array();
    $message['body'][] = drupal_wrap_mail(drupal_html_to_text(mail_edit_format($template['body'], $data, $options)));
}

/**
 * @param $type int, element type (subject or body) @see MAIL_EDIT_TEST_SUBJECT, MAIL_EDIT_TEST_BODY
 * @param $language
 * @param array $variables
 * @param bool $replace
 * @return mixed|null|string
 */
function _mail_edit_test_text($type, $language, array $variables, $replace = TRUE) {
    $text = '';
    switch($type) {
        case MAIL_EDIT_TEST_SUBJECT:
            $text = t('Node content of [node:title]');
            break;
        case MAIL_EDIT_TEST_BODY:
            $text = <<<TXT
Node title: [node:title]

[node:body]

See it at [node:url]
TXT;
            break;
    }
    if ($replace) {
        return token_replace($text, $variables, array('langcode' => $language));
    }
    return $text;
}